using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;

namespace ElasticToolCon
{
    public class TranslationMemoryXmlParser
    {
        private string XmlFilePath;

        public TranslationMemoryXmlParser(string path)
        {
            this.XmlFilePath = path;
        }

        public IEnumerable<TranslationMemory> Parse()
        {
            XmlSerializer serializer = new XmlSerializer(typeof(dataroot));
            dataroot xmlData = (dataroot)serializer.Deserialize(new XmlTextReader(XmlFilePath));
            List<TranslationMemory> result = new List<TranslationMemory>();
            foreach (var data in xmlData.Items.AsEnumerable())
            {
                TranslationMemory tm = new TranslationMemory();
                tm.id = Convert.ToInt32(data.id);
                tm.japanese = data.source_segment;
                tm.chinese = data.target_segment;
                tm.tags += data.creation_date + Environment.NewLine;
                tm.tags += data.creation_user + Environment.NewLine;
                result.Add(tm);
            }
            return result;
        }
    }

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34014
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class dataroot
    {

        private datarootTranslation_Memory[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Translation_Memory", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datarootTranslation_Memory[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class datarootTranslation_Memory
    {

        private string fileField;

        private string idField;

        private string source_languageField;

        private string source_segmentField;

        private string target_languageField;

        private string target_segmentField;

        private string creation_dateField;

        private string creation_userField;

        private string change_dateField;

        private string change_userField;

        private string last_used_dateField;

        private string last_used_userField;

        private string usage_counterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source_language
        {
            get
            {
                return this.source_languageField;
            }
            set
            {
                this.source_languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source_segment
        {
            get
            {
                return this.source_segmentField;
            }
            set
            {
                this.source_segmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string target_language
        {
            get
            {
                return this.target_languageField;
            }
            set
            {
                this.target_languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string target_segment
        {
            get
            {
                return this.target_segmentField;
            }
            set
            {
                this.target_segmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string creation_user
        {
            get
            {
                return this.creation_userField;
            }
            set
            {
                this.creation_userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string change_date
        {
            get
            {
                return this.change_dateField;
            }
            set
            {
                this.change_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string change_user
        {
            get
            {
                return this.change_userField;
            }
            set
            {
                this.change_userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_used_date
        {
            get
            {
                return this.last_used_dateField;
            }
            set
            {
                this.last_used_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_used_user
        {
            get
            {
                return this.last_used_userField;
            }
            set
            {
                this.last_used_userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usage_counter
        {
            get
            {
                return this.usage_counterField;
            }
            set
            {
                this.usage_counterField = value;
            }
        }
    }
}
